// Regenerates supabase/remote_seed.sql from the holes currently in the remote
// NUNI project (PO, 2026-09-23, Q63): the holes imported from LsgScores and
// repositioned by hand, plus the ones created in the app since, survive a
// schema reconstruction by being replayed from this file. Run from the repo
// root, then review and commit the diff:
//
//   fvm dart run tool/export_remote_seed.dart [--env env/migration.json]
//
// Reads with the NUNI service key (same untracked key file as
// tool/migrate_lsgscores.dart; only the NUNI_* keys are used).
import 'dart:convert';
import 'dart:io';

import 'package:supabase/supabase.dart';

const _outputPath = 'supabase/remote_seed.sql';

/// LsgScores holes never kept in NUNI (mirrors `excludedLegacyHoleIds` in
/// migrate_lsgscores.dart).
const _excludedLegacyIds = {32};

Future<void> main(List<String> args) async {
  final envIndex = args.indexOf('--env');
  final envPath = envIndex >= 0 && envIndex + 1 < args.length
      ? args[envIndex + 1]
      : 'env/migration.json';
  final env = (jsonDecode(File(envPath).readAsStringSync()) as Map)
      .cast<String, Object?>();
  final nuni = SupabaseClient(
    env['NUNI_SUPABASE_URL']! as String,
    env['NUNI_SUPABASE_SERVICE_KEY']! as String,
  );
  try {
    final rows = await nuni
        .from('holes')
        .select(
          'id, owner_id, name, description, par, distance_m, start_lat, '
          'start_lng, end_lat, end_lng, path, photo_start_path, '
          'photo_end_path, visibility, legacy_id, created_at, updated_at',
        )
        .order('created_at', ascending: true);
    final kept = [
      for (final row in rows)
        if (!_excludedLegacyIds.contains(row['legacy_id'])) row,
    ];
    File(_outputPath).writeAsStringSync(_render(kept));
    stdout.writeln('${kept.length} holes written to $_outputPath.');
  } finally {
    await nuni.dispose();
  }
}

String _render(List<Map<String, dynamic>> holes) {
  final buffer = StringBuffer()
    ..writeln(
      '-- Remote seed data: the holes of the real "nuni" project, replayed after a schema',
    )
    ..writeln(
      '-- reconstruction (AGENTS.md point 8, docs/DEV.md) so they come back without re-creating',
    )
    ..writeln(
      '-- anything -- their photos already sit in the "holes" storage bucket, which a',
    )
    ..writeln('-- reconstruction never touches (only the schema is rebuilt).')
    ..writeln('--')
    ..writeln(
      '-- GENERATED by tool/export_remote_seed.dart -- do not edit by hand, re-run the tool after',
    )
    ..writeln(
      '-- editing holes in the app. Since 2026-09-23 (Q63) it holds the holes imported from LsgScores',
    )
    ..writeln(
      '-- (legacy_id set, repositioned by the PO) and the ones created in the app since; legacy_id is',
    )
    ..writeln(
      '-- kept so the LsgScores session import (plan 13, step 2) finds them, and so replaying',
    )
    ..writeln(
      '-- tool/migrate_lsgscores.dart holes after this file inserts nothing.',
    )
    ..writeln('--')
    ..writeln(
      '-- Distinct from supabase/seed.sql (local-Docker-only fixtures). Owner is the PO\'s own',
    )
    ..writeln(
      '-- auth.users row, untouched by a reconstruction, so the ids stay valid across replays.',
    )
    ..writeln()
    ..writeln('insert into holes (')
    ..writeln(
      '  id, owner_id, name, description, par, distance_m, start, end_point, path,',
    )
    ..writeln(
      '  photo_start_path, photo_end_path, visibility, legacy_id, created_at, updated_at',
    )
    ..writeln(') values');
  for (var i = 0; i < holes.length; i++) {
    final h = holes[i];
    final values = [
      _text(h['id']),
      _text(h['owner_id']),
      _text(h['name']),
      _text(h['description']),
      '${h['par']}',
      _number(h['distance_m']),
      _point(h['start_lat'], h['start_lng']),
      _point(h['end_lat'], h['end_lng']),
      h['path'] == null ? 'null' : '${_text(jsonEncode(h['path']))}::jsonb',
      _text(h['photo_start_path']),
      _text(h['photo_end_path']),
      _text(h['visibility']),
      _number(h['legacy_id']),
      _text(h['created_at']),
      _text(h['updated_at']),
    ];
    buffer
      ..writeln('  (')
      ..writeln(values.map((v) => '    $v').join(',\n'))
      ..writeln(i == holes.length - 1 ? '  )' : '  ),');
  }
  buffer.writeln('on conflict do nothing;');
  return buffer.toString();
}

String _text(Object? value) =>
    value == null ? 'null' : "'${value.toString().replaceAll("'", "''")}'";

String _number(Object? value) => value == null ? 'null' : '$value';

String _point(Object? lat, Object? lng) =>
    lat == null || lng == null ? 'null' : "'SRID=4326;POINT($lng $lat)'";
